txt = "Hello, and welcome to my world."
a = txt.capitalize()
b= txt.casefold()
c = txt.center(20)
d = txt.count("welcome")
e = txt.encode()
f = txt.endswith(".")
g = txt.find("welcome")
h = txt.index("welcome")
i = txt.upper()
j = txt.lower()
print (a)
print (b)
print (c)
print (d)
print (e)
print (f)
print (g)
print (h)
print (i)
print (j)
